### ISSUE TITLE
logline

### ISSUE THREAD

**Issue by aiq** [aiq/luazdf#9]
I am a little irritated about the order of the error level.
My natural assumption would be reverse. 

ERROR > 75
DEBUG > 50
INFO > 25
VERBOSE > 0

It feels more natural for me if a more important case has a higher number.

**Comment by pocomane** [comment]
I choose them in this way because I initially thought to that values as the "Thresholds at which a certain kind of log should be enabled". So a most severe log should have a smaller threshold.

However I agree that as it is the codes are misleading. Maybe we can invert all the comparison and loop senses? Or we could use more meaningful names (e.g. ERROR_THRESHOLD, WARN_THRESHOLD, and so on)?

**Comment by aiq** [comment]
I did some talk with others and most find your approach, with higher number equals more output, better. I think it is ok the current way.

**Comment by aiq** [comment]
I did some talk with others and most find your approach, with higher number equals more output, better. I think it is ok the current way.
